# the config for current running
pipeline: transmil

dataset:
  data_path: "data/camelyon16/dsmil_files"
  csv_path: "data/split/camelyon16"
  fold: fold_1
  batch_size: 1
  num_workers: 8

model:
  name: abmil
  input_dim: 512
  embed_dim: 512
  num_classes: 2

optim:
  optimizer: Adam
  loss: ce
  # gradient clipping
  clip: 
  lr: 5.e-4
  weight_decay: 1.e-4
  epochs: 100
  save_period: 1
  betas: 
  # lr_scheduler: if warmup, the step will be 
  lr_scheduler: warmup 
  step_size: 10
  amsgrad: true

stat:
  monitor:
    mode: "max"
    metric: "AUC"
    early_stop: 10
    metric_curves: false
    display_port: 8099
  record_dir: output
  resume:

misc:
  # the name only for this running, not the task
  running_name: 'camelyon16/abmil/mfc'
  cuda: "1"
  seed: 2024  
