# the config for current running
pipeline: dsmil

dataset:
  data_path: "data/Camelyon16_ctrans_baseline/pt_files"
  # data_path: "data/nsclc/pt_files"
  csv_path: "data/split/camelyon16"
  # csv_path: "data/split/nsclc"
  fold: fold_1
  batch_size: 1
  num_workers: 8

model:
  name: dsmil
  input_dim: 768
  embed_dim: 512
  num_classes: 2

optim:
  optimizer: Adam
  loss: bce
  # gradient clipping
  clip: 
  lr: 0.0001
  weight_decay: 1.e-4
  betas: [0.5, 0.9]
  epochs: 100
  save_period: 1
  # lr_scheduler: if warmup, the step will be 
  lr_scheduler: warmup 
  step_size: 10
  amsgrad: true

stat:
  monitor:
    mode: "max"
    metric: "AUC"
    early_stop: 30
    metric_curves: false
    display_port: 8099
  record_dir: output
  resume:

misc:
  # the name only for this running, not the task
  # running_name: 'nsclc/dsmil/MFC'
  running_name: 'camelyon16/dsmil/base_ctrans'
  cuda: "1"
  seed: 666
  
